import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ServizioDatiService {

  mostre = [
    {nome: "La Gioconda (Mona Lisa)", artista: "Leonardo da Vinci", descrizione: "Questo celebre dipinto è probabilmente l'opera più famosa del Louvre e una delle più iconiche al mondo, conosciuta per il misterioso sorriso della donna ritratta.", datainizio: "1 marzo 2024", datafine: "30 aprile 2024", immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/640px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"},
    {nome: "La Venere", artista: "Milo", descrizione: "Questa statua greca rappresenta Afrodite, la dea dell'amore e della bellezza, ed è una delle sculture più famose e ammirate del Louvre.",datainizio: "15 marzo 2024", datafine: "30 aprile 2024", immagine: "https://www.didatticarte.it/Blog/wp-content/uploads/2022/06/venere-milo-tre-quarti.jpg"},
    {nome: "La Vittoria", artista: "Samotracia", descrizione: "Questa scultura greca raffigura Nike, la dea della vittoria, ed è una delle più impressionanti opere dell'arte ellenistica nel museo", datainizio: "10 aprile 2024", datafine: "30 may 2024", immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg/800px-Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg"},
    {nome: "La Libertà che guida il popolo", artista: "Eugène Delacroix", descrizione: "Questo dipinto rappresenta uno dei momenti più iconici della Rivoluzione Francese ed è un simbolo della lotta per la libertà e l'indipendenza.",datainizio: "5 aprile 2024", datafine: "30 may 2024", immagine: "https://www.artesvelata.it/wp-content/uploads/2020/10/Eugene-Delacroix-La-Liberta-che-guida-il-popolo-Particolare-della-Liberta-arte-svelata.jpg"},
    {nome: "Le Nozze di Cana", artista: "Paolo Veronese", descrizione: "Questo grande dipinto rappresenta una scena biblica del Nuovo Testamento ed è una delle opere più celebri del Rinascimento italiano nel Louvre.",datainizio: "20 marzo 2024", datafine: "30 aprile 2024", immagine: "https://cdn.studenti.stbm.it/images/2016/12/13/nozze-di-cana---paolo-veronese_400x600.jpeg"},
    {nome: "La Cappella Sistina", artista: "Michelangelo", descrizione: "Il Louvre ospita una replica in scala ridotta della celebre Cappella Sistina, che permette ai visitatori di ammirare i famosi affreschi di Michelangelo, inclusa la Creazione di Adamo.",datainizio: "1 aprile 2024", datafine: "30 may 2024", immagine: "https://cdn.studenti.stbm.it/images/2016/11/03/giudizio-universale-di-michelangelo_400x600.jpeg"},
    {nome: "L'Incoronazione di Napoleone", artista: "Jacques-Louis David", descrizione: "Questo maestoso dipinto raffigura l'incoronazione di Napoleone Bonaparte come imperatore e rappresenta un importante momento della storia francese nel XIX secolo.",datainizio: "25 marzo 2024", datafine: "30 aprile 2024", immagine: "https://www.fremondoweb.com/wp-content/uploads/2020/12/Incoronazione-di-Napoleone-Jacques-Louis-David-analisi-1024x643-1-266x266.png"}
  ]

  dettagli_mostre = [
    {nome: "La Gioconda (Mona Lisa)", anno: "1503-1506", artista: "Leonardo Da Vinci", ulteriori_info: "La Gioconda è stata oggetto di numerosi studi e analisi scientifiche nel corso degli anni, contribuendo a svelare alcuni dei misteri che circondano l'opera, inclusa l'identità della donna ritratta e le tecniche pittoriche utilizzate da Leonardo da Vinci.", descrizione: "Questo celebre dipinto, realizzato da Leonardo da Vinci all'inizio del XVI secolo, è una delle opere d'arte più famose e iconiche al mondo. <br> Ritrae una donna di cui si presume essere Lisa Gherardini, moglie di un ricco mercante fiorentino. <br> La sua enigmatica espressione ha affascinato e ispirato generazioni di spettatori. <br> La Gioconda è esposta all'interno del Louvre in una sala appositamente dedicata, dove attira milioni di visitatori ogni anno.", immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/640px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"},
    {nome: "La Venere", anno: "Periodo ellenistico, circa 130-100 a.C.", artista: "Milo", ulteriori_info: "La mancanza delle braccia della Venere di Milo ha alimentato numerose teorie e speculazioni sulle circostanze della sua scoperta e sul possibile aspetto originale della statua.", descrizione: "Conosciuta anche come Afrodite di Milo, questa statua greca risale al periodo ellenistico e rappresenta la dea dell'amore e della bellezza. <br> Scoperta sull'isola di Milo nel 1820, la statua è famosa per la sua grazia e la sua aura di mistero, specialmente per la sua mancanza di braccia. <br> La Venere di Milo è esposta nella sala delle sculture greche del Louvre, dove si erge maestosamente come uno dei capolavori più celebri della collezione.", immagine: "https://www.didatticarte.it/Blog/wp-content/uploads/2022/06/venere-milo-tre-quarti.jpg"},
    {nome: "La Vittoria", anno: "II secolo a.C.", artista: "Samotracia", ulteriori_info: "La Vittoria di Samotracia è stata restaurata e rimontata più volte nel corso dei secoli per preservarne la sua integrità strutturale e la sua bellezza artistica.", descrizione: "Questa scultura greca risalente al II secolo a.C. raffigura Nike, la dea della vittoria, in una maestosa posa alata su una prua di nave. <br> Conosciuta anche come Nike di Samotracia, la statua è famosa per il suo dinamismo e la sua eleganza, nonostante la mancanza di testa e braccia. <br> La Vittoria di Samotracia è esposta nella scalinata Daru del Louvre, dove la sua presenza imponente incanta i visitatori che salgono le scale.", immagine: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg/800px-Victoire_de_Samothrace_-_Musee_du_Louvre_-_20190812.jpg"},
    {nome: "La Libertà che guida il popolo", anno: "1830", artista: "Eugène Delacroix", ulteriori_info: "Il dipinto di Delacroix è stato oggetto di controversie politiche e artistiche nel corso dei decenni, in quanto è stato interpretato sia come un simbolo di libertà e rivoluzione che come un'opera che esalta la violenza della guerra.", descrizione: "Questo dipinto, realizzato da Eugène Delacroix nel 1830, raffigura una scena iconica della Rivoluzione Francese: il popolo parigino in rivolta. <br> Al centro dell'opera si erge una figura allegorica della Libertà, che guida il popolo con la bandiera francese sventolante. <br> La Libertà che guida il popolo è esposta nella sezione di pittura francese del Louvre, dove continua a essere una delle opere più ammirate e discusse.", immagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqjOz365dg1xiwW72UYtDhavFVgx9Pa6vc1PDxXhuq2w&s"},
    {nome: "Le Nozze di Cana", anno: "1563", artista: "Paolo Veronese", ulteriori_info: "Il dipinto di Veronese è stato commissionato per decorare il refettorio del monastero di San Giorgio Maggiore a Venezia e è stato trasferito al Louvre dopo la Rivoluzione Francese.", descrizione: "Questo maestoso dipinto del XVI secolo raffigura il miracolo compiuto da Gesù durante le nozze di Cana, come descritto nel Vangelo di Giovanni. <br> Paolo Veronese cattura il momento in cui Gesù trasforma l'acqua in vino, creando una scena ricca di dettagli e movimento. <br> Le Nozze di Cana è esposta nella Grande Galleria del Louvre, dove la sua grandiosità e la sua brillantezza cromatica lasciano senza fiato i visitatori.", immagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ_3EpnflEPRqmSLhkxmTjOWCeKHsF05ORoeoj3fu5wA&s"},
    {nome: "La Cappella Sistina", anno: "1508-1512", artista: "Michelangelo", ulteriori_info: "La replica della Cappella Sistina è stata realizzata per consentire ai visitatori del Louvre di ammirare da vicino alcuni dei capolavori più celebrati della storia dell'arte, senza la necessità di viaggiare fino a Roma.", descrizione: "Questa replica in scala ridotta della celebre Cappella Sistina di Michelangelo permette ai visitatori di ammirare i suoi famosi affreschi. <br> Tra le opere più celebri esposte si trovano la Creazione di Adamo e il Giudizio Universale, che mostrano il genio artistico di Michelangelo. <br> La Cappella Sistina è esposta nel Dipartimento delle Arti Grafiche del Louvre, dove offre agli spettatori un'esperienza unica nel riprodurre l'atmosfera e la grandiosità dell'originale.", immagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRMgf_ecLRJc1aUghH0VH_bD92IPzRURWvTEm85TfiRg&s"},
    {nome: "L'Incoronazione di Napoleone", anno: "1804", artista: "Jacques-Louis David", ulteriori_info: "Il dipinto di David è stato commissionato dallo stesso Napoleone per commemorare la sua incoronazione e sottolineare la legittimità del suo governo. La scelta dei dettagli e dei simboli nell'opera riflette il desiderio di Napoleone di legittimare il proprio potere attraverso l'arte e la propaganda visiva.", descrizione: "Questo maestoso dipinto realizzato da Jacques-Louis David nel 1804 raffigura l'incoronazione di Napoleone Bonaparte come imperatore. <br> L'opera cattura il momento solenne della cerimonia all'interno della Cattedrale di Notre-Dame, con Napoleone che incorona sé stesso e Giuseppina. <br> L'Incoronazione di Napoleone è esposta nella Grande Galleria del Louvre, dove la sua grandezza e il suo realismo storico continuano a impressionare i visitatori.", immagine: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs5LvT6NuTEpD30szQskkl_VO5MZVbnMiTZBjUjhIfog&s"}
  ]
  
  constructor() { }


}
